# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a5536ec6abc727cdfb194575387535692d91023c666a8e036ac75a45e1395f8ba5cdd37fcc8fc62e983e883edbe5f28f55ff7dded9c9d2db624ac14be500bdd

test:
  secret_key_base: c240d86372af7ff8ecf94af507e56e1cd9496181e1336788cf516ec42774b5fd1f10cf2a779261f1cfe033200b038536126841d119a46171eeb628767d0f705f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
